### ISSUE TITLE
"Scale" article

### ISSUE THREAD

**Issue by bartekn** [stellar/docs#108]
There are a lot of questions recently about Stellar scale. Would be great to create an article about stress tests and other similar information.

**Comment by theaeolianmachine** [comment]
Going to close this out in favor of the document that Graydon wrote in stellar-core: https://github.com/stellar/stellar-core/blob/master/docs/software/performance.md.

This is visible on the website: https://www.stellar.org/developers/stellar-core/software/performance.html
