### ISSUE TITLE
Improve descriptions of operations in list of operations

### ISSUE THREAD

**Issue by irisli** [stellar/docs#120]
The descriptions for each of the operations are not parallel and consistent in how they are explained.
https://www.stellar.org/developers/learn/concepts/list-of-operations.html#path-payment

Examples of non-parallelism:
- First person: `Allows you to set,modify or delete a Data Entry (name/value pair) that is attached to a particular account.`
- Action: `Sends an amount in a specific asset to a destination account.`
- Overview description: `A passive offer is an offer that does not act on and take a reverse offer of equal price.`
- "this" description: `This operation sets the options for an account.`

**Comment by theaeolianmachine** [comment]
Going to change these all to actions.
