### ISSUE TITLE
Remove “XDR Viewer” link in tools

### ISSUE THREAD

**Issue by Mr0grog** [stellar/docs#121]
The link to XDR Viewer on the [tools page](https://github.com/stellar/docs/blob/master/tools/readme.md) just goes to a page that says “Deprecated. Use Laboratory.” So we should probably just get rid of the link.

Unless sending people to the source of this tool still serves some particular value?

**Comment by jessica-collier** [comment]
It does not serve any particular value that I know of. @irisli?

**Comment by irisli** [comment]
The XDR viewer was just recently deprecated and the developers site did not get updated.

I have removed it in this PR: https://github.com/stellar/docs/pull/123

**Comment by Mr0grog** [comment]
Sweet! 👍
