### ISSUE TITLE
The Anchor guide should be revamped

### ISSUE THREAD

**Issue by Mr0grog** [stellar/docs#151]
Much of what’s covered in the existing anchor guide is now better covered in the new “Get Started” guide. The anchor guide should be re-written to focus on compliance, federation server, and bridge server, generally following these diagrams:
- https://www.stellar.org/wp-content/uploads/2016/06/Sending-Payment-Flow-Detailed.jpg
- https://www.stellar.org/wp-content/uploads/2016/06/Receiving-Payment-Flow-Detailed.jpg

**Comment by Mr0grog** [comment]
This is being fixed in #160.

**Comment by theaeolianmachine** [comment]
Closed by #160.
