### ISSUE TITLE
Federation & Compliance Protocol docs should be siblings

### ISSUE THREAD

**Issue by Mr0grog** [stellar/docs#166]
The Federation Protocol and Compliance Protocol docs should really be siblings at the same level of hierarchy—they are both discussing conceptually similar things in terms of how they relate to the Stellar ecosystem.

Not sure if this is directly under guides or under guides/concepts, but one should move. (Any opinions @jedmccaleb @bartekn?)

**Comment by theaeolianmachine** [comment]
Closing this out, as it's quite feasible for an organization to want to use federation but not compliance, or at the minimum, implement federation lookup.
