### ISSUE TITLE
Update anchor guide for next bridge/compliance release

### ISSUE THREAD

**Issue by Mr0grog** [stellar/docs#167]
There were several bugs in the current release of 0.0.12 that make the new anchor guide a little bit more complex than need be; this issue is to track updates that need to be made to reflect fixes in the next releases, since we don't know exactly when they will land relative to the guide (and the guide is still in flux so I don't really want to branch it).
- [ ] `source` param no longer necessary in bridge requests if specified in configuration: https://github.com/stellar/bridge-server/issues/28

**Comment by theaeolianmachine** [comment]
Closing this out in favor of completely refactoring the anchor/issuer guide.
