### ISSUE TITLE
Core docs page loads w/o CSS

### ISSUE THREAD

**Issue by mozzadrella** [stellar/docs#174]
This is what loads at https://www.stellar.org/developers/stellar-core/

![screen shot 2016-11-07 at 10 25 13 am](https://cloud.githubusercontent.com/assets/1874003/20063304/aa69a6ac-a4d4-11e6-9395-b944bb923bc6.png)

**Comment by irisli** [comment]
The reason for this is that those docs were not intended to be viewed on the developers site.
