### ISSUE TITLE
`tx_bad_auth` error not listed in List of Operations page

### ISSUE THREAD

**Issue by ramontayag** [stellar/docs#179]
I was using the [laboratory](www.stellar.org/laboratory) and got an error (`tx_bad_auth`) that wasn't listed in [the list of operations page](https://www.stellar.org/developers/learn/concepts/list-of-operations.html) like it says it should.

```json
{
  "type": "https://stellar.org/horizon-errors/transaction_failed",
  "title": "Transaction Failed",
  "status": 400,
  "detail": "The transaction failed when submitted to the stellar network. The `extras.result_codes` field on this response contains further details.  Descriptions of each code can be found at: https://www.stellar.org/developers/learn/concepts/list-of-operations.html",
  "instance": "horizon-testnet-001/vbcLOvVIaT-190963",
  "extras": {
    "envelope_xdr": "AAAAAMEgWGo+2qai/OlmWY9KFFz9RODu1FEo4/4MydyyhAVKAAAAZABLtbkAAAABAAAAAAAAAAAAAAABAAAAAAAAAAYAAAABUEhQAAAAAAAYpvovNEzEX3wa8E1WRK3RrvY99f7lt31vKKJiKihY6X//////////AAAAAAAAAAEqKFjpAAAAQFJXmUxJO+gyKyj3HiDMi1WYsV33/DhTyBAavhYpsffe6El0eLAzIQFY8FFOSVTKA694m5zW2YFdUVrzFR7rYA8=",
    "result_codes": {
      "transaction": "tx_bad_auth"
    },
    "result_xdr": "AAAAAAAAAGT////6AAAAAA=="
  }
}
```

**Comment by bartekn** [comment]
List of operations page contains operations related errors. For transaction errors check: https://www.stellar.org/developers/horizon/reference/errors/transaction-failed.html

**Comment by s-a-y** [comment]
+1, this is still confusing
Error description doesn't point in the right direction. Even link you posted doesn't have any information about tx_bad_auth

**Comment by zallarak** [comment]
I am having the same problem. Can someone please shed some light on this? The documentation doesn't need to be addressed, but having an idea of what it means is important to me in the short run. Thank you.

**Comment by oryband** [comment]
This issue is still relevant. No direction in docs what this error mean.

**Comment by oryband** [comment]
From Stellar Slack:
>>> Bad auth means that the signature is for a different network or by a different key than required.

**Comment by bartekn** [comment]
https://www.stellar.org/developers/guides/concepts/transactions.html#possible-errors

**Comment by ChrisCates** [comment]
Hi, I'm assuming I'm getting `op_bad_auth` because of code `-6` correct?
If it wasn't literally 5am, I'd set up a federated server... I just need some sleep.

**Comment by bartekn** [comment]
Tracking in #507.

**Comment by ryancarville** [comment]
Hello everyone,
SO I am getting `tx_bad_auth` on a new account creation.  The correct network settings are present.  Please help and an advanced thank you!

**Comment by d3vild06** [comment]
Same here. Took the same steps as @ryancarville Not sure what's going on but keep getting the same error on the testnet.

**Comment by ryancarville** [comment]
@d3vild06 i figured out my issue. My issuing asset account thresholds were being changed before issuing the asset to the distribution account. So when signing it was a bad auth because the thresholds were set to 0.
