### ISSUE TITLE
Payment to multiple parties

### ISSUE THREAD

**Issue by pipaman** [stellar/docs#190]
Hi,
I would like to code a dividend payout account. The idea is simple, every dollar which comes to account A shoud be divided in different % to each account A1, ..., An
Is this possible to code with Stellar?
Is it possible to receive USD and keep that currency to payout?

Thanks on advance.
P/

**Comment by jedmccaleb** [comment]
Hi pipaman, questions are better suited for either slack.stellar.org  or https://galactictalk.org/
but yeah you can do something like that with stellar.
