### ISSUE TITLE
Stellar brief

### ISSUE THREAD

**Issue by wassimhattab** [stellar/docs#207]
Hello,

I'm new to stellar o tried to create new account by getting secret and public key and get the account info and send transaction and foreach transaction my balance was decremented by the amount sent + 0.00001.. this was all test account or dunno what i should call.

But if i want to work on project where i can integrate stellar when i want to create a new account for a client with start amount how stellar will collect the amount and how can i track the payment ..

And me as a company how i'll be charged from stellar and When someone create an account or want to fund his account how stellar will collect the money?

Thank you on advance.

**Comment by theaeolianmachine** [comment]
Closing this out, as it's a question best answered in other forums. I would suggest posting this question in Stellar's [Keybase](https://keybase.io/team/stellar.public) or [Stack Exchange](https://stellar.stackexchange.com/), as you'll likely get a good answer there!
