### ISSUE TITLE
get started docs should mention gostellar.org

### ISSUE THREAD

**Issue by gouth7** [stellar/docs#212]
Maybe a line at the top of the compliance section that says:

"We recommend using gostellar.org for testing this. "

**Comment by bartekn** [comment]
Can you make a PR? I'll be happy to merge.

**Comment by theaeolianmachine** [comment]
@bartekn do you still think this is valuable to do, or is this something that we shouldn't draw attention to (I'm not sure how much love gostellar.org gets these days).

**Comment by theaeolianmachine** [comment]
Actually, going to go ahead and just do this.

**Comment by bartekn** [comment]
> I'm not sure how much love gostellar.org gets these days

I think it should still work but I think it's not actively maintained... Also, if there are any breaking changes to Compliance Protocol it can stop working.

So I guess we can link it but make sure that it's updated to be up to date with the protocol.
