### ISSUE TITLE
Improve channel documentation

### ISSUE THREAD

**Issue by andywer** [stellar/docs#215]
Hey guys,

I really like the stellar documentation. It's well structured and explains the network's features really well. There is just one page that left me with more questions than answers: [The channels page](https://github.com/stellar/docs/blob/master/guides/channels.md).

So a channel is really not a thing on its own, but just another account to sign the transaction. What I am not sure about:

* I suppose the channel account has to be activated with 20 XLM as well (?)
* Code sample: What are `channelAccounts`, `channelKeys` and `channelIndex`?
* Code sample: Why multiple channel accounts, keys, ... and not just one?

**Comment by jedmccaleb** [comment]
updated
