### ISSUE TITLE
Need clarification - Seed vs Key

### ISSUE THREAD

**Issue by Reiiya** [stellar/docs#228]
During creation of a new node, one of the steps is assigning node an identity by writing **Secret Seed** into config file. For this purpose I've been using [Stellar Laboratory](https://www.stellar.org/laboratory/#account-creator?network=test).

However laboratory states that it generates Public Key and **Secret Key**. Why do my nodes then still work as intended if I use this key instead of seed?

**Comment by jedmccaleb** [comment]
These are the same thing.

Zach the issue here is to make sure the naming is consistent. It should all be "Secret key".  Can you comb through and either change in docs where you can or create an issue in the appropriate repo if it is in code.

**Comment by Reiiya** [comment]
I contributed on this. Made a PR #229 changing "secret seed" to "secret key" in text. I suppose code snippets have to be reviewed as well.

**Comment by nikhilsaraf** [comment]
added a comment to your PR, we don't need this issue anymore.
