### ISSUE TITLE
"Stellar Core" hyperlink under Software tab in docs is a 404

### ISSUE THREAD

**Issue by MarijnStam** [stellar/docs#277]

**Comment by bartekn** [comment]
Works for me. Could you point me to the link that doesn't work for you?

**Comment by MarijnStam** [comment]
On this [page](https://github.com/stellar/docs/tree/master/software) when I click the Stellar Core hyperlink I get redirected to: https://github.com/stellar/docs/blob/master/stellar-core/learn/admin.html which is a 404.

**Comment by bartekn** [comment]
OK, this repository is only a source for the docs that are deployed to https://www.stellar.org/developers/ so links may not work in GitHub. You can see that it works fine here: https://www.stellar.org/developers/software/
