### ISSUE TITLE
SBC submission field length limit

### ISSUE THREAD

**Issue by Synesso** [stellar/docs#281]
_This issue is not entirely related to this repo, but it's kind of related. If it could find its way to the right person, I'd appreciate it._

The [6th Stellar Build Challenge submission form](https://stellarform.typeform.com/to/ZeXJ2t) has the field 8.a:

> How do you summarize your project?

This text field is limited to only 40 characters. This is too short for meaningful answers and much shorter than answers provided by [submissions in previous SBCs](https://www.stellar.org/blog/fourth-stellar-build-challenge-results/). I suspect it's been changed in error.

**Comment by bartekn** [comment]
Reported to SBC team.

**Comment by asfink** [comment]
As an FYI, the next question after this one on the application asks for more information about your project, where you can put a longer explanation.
