### ISSUE TITLE
Where do we go to get the Destination tag in the wallet?

### ISSUE THREAD

**Issue by agentzero2** [stellar/docs#29]
question in title.

**Comment by bekkibolthouse** [comment]
Hi @agentzero2, here's our [doc about Destination Tags](https://github.com/stellar/docs/blob/master/docs/Destination-Tags.md). The dt is typically set by a gateway and is provided to the user.The destination tag is like the memo field on a check, and is useful for the gateway to keep track of which account should receive the credit.  The gateway itself maintains a mapping of destination tags --> accounts.  The dt is not "tracked" by stellar; so you can't "get" it by calling the API. It is passed through like metadata.  Hope this helps, if not - find me on IRC as Bekki, and I'd be happy to chat more.

**Comment by bekkibolthouse** [comment]
This document has been moved to https://github.com/stellar/docs/blob/master/old-docs/Destination-Tags.md

This document is no longer maintained. The concept of destination tags does not persist in the new stellar-core network. Closing this conversation.
