### ISSUE TITLE
Documentation doesn't reset scroll when clicking on commands in the left hand menu

### ISSUE THREAD

**Issue by thomasdavis** [stellar/docs#30]
Very beautiful documentation and it feels snappy. But if you scroll down and click on `validation_create`, the hash tag changes and the content changes but you have to scroll back up to see the new content.

**Comment by adrian510** [comment]
https://cointellect.com/?code=6b332ae2

**Comment by bartekn** [comment]
What's the name of your browser and it's version? Seems to be working OK for me.

**Comment by bekkibolthouse** [comment]
Hi @thomasdavis has this problem persisted for you? Please let us know.
