### ISSUE TITLE
off-line Stellar/CURRENT-REPOSITORY 

### ISSUE THREAD

**Issue by EvertonMelo** [stellar/docs#328]
URL erro 404 

https://github.com/stellar/CURRENT-REPOSITORY/tree/master/src

 date > 
Ter Mar 27 19:01:57 -03 2018 && 
```
wget https://github.com/stellar/CURRENT-REPOSITORY/tree/master/src

--2018-03-27 19:02:10--  https://github.com/stellar/CURRENT-REPOSITORY/tree/master/src
Resolvendo github.com (github.com)... 192.30.253.113, 192.30.253.112
Conectando-se a github.com (github.com)|192.30.253.113|:443... conectado.
A requisição HTTP foi enviada, aguardando resposta... 404 Not Found
```
**2018-03-27 19:02:11 ERRO 404: Not Found**.

**Comment by bartekn** [comment]
`https://github.com/stellar/CURRENT-REPOSITORY` doesn't exist. Please install `git` and run `git clone git@github.com:stellar/docs.git`.
