### ISSUE TITLE
add support Brazilian Portuguese.

### ISSUE THREAD

**Issue by EvertonMelo** [stellar/docs#329]
add support Brazilian Portuguese on official documentation.

**Comment by bartekn** [comment]
We won't be able to maintain it as there are no Portuguese-speaking team members. Please use translators or connect with Stellar developers in your country.

**Comment by EvertonMelo** [comment]
@bartekn with all respect. 

if the person responsible for the translation did a good job, that topic would not have been opened.

and if you want contributions, you name it or even a way to contact this "Portuguese-speaking" 

so, 

Thank you for making clear how much the contribution policy is obscure.
 
also thank you very much, for saying that you are aware of the deficiencies that the stellar project has in other languages, 

thank goodness that knowing does not imply doing something about.

precisely this mentality that produces a fertile environment for  0-day vulnerability. 

Good luck to you, because you will need it.

**Comment by bartekn** [comment]
Translating documentation is not as simple as finding a translator, you have to prepare the documentation app to handle translations, keep them up to date, etc. Even big corporations (FB/Google) have their official docs in English only.

It's not that I wouldn't want to have docs in many different languages. It's just super hard to maintain a good quality of them.

**Comment by EvertonMelo** [comment]
sure, 
**_Translating documentation is not as simple as finding a translator, you have to prepare the documentation app to handle translations, keep them up to date, etc._**
( I understand it is not simple but github can help a lot ) 

for example 
https://github.com/stellar/docs/blob/master/guides/get-started/readme.md
( **last Update **30 Nov 2016**** ) 

Does this document explain in general how to start right?
in Stellar.org maintains, does not contain information on the number of SDK versions.

examplo:

java 8 > above 
JS 1.8 > above.
Go 1.3 > above. 

the number is not explicit but a link to sdk, which would be more manageable.

but you can say that your code is not vulnerable, so it omits the requirements.
see what an omission like this can cause:

for java:
https://www.cvedetails.com/vulnerability-list/vendor_id-93/product_id-19116/version_id-212962/Oracle-JDK-8.0.html
For JS( version example, can be much worse. ) 
http://www.virusradar.com/update/info/16076 
or GO lang ( there is a CVE for each version I just exposed one ) 
https://www.cvedetails.com/vulnerability-list/vendor_id-14185/product_id-29205/version_id-172608/Golang-GO-1.3.html 

I also understand that documentation is something heavy, but there are a number of things that can be translated that are static in the case of Blockchains projects.

FB, Goo.gl are not companies that use blockchain, 

but Okey.

but that way you have the opportunity to be better than them right? and yet you do not?

It's not that I wouldn't want to have docs in many different languages. It's just super hard to maintain a good quality of them.

I do not understand when you speak "good quality", because 

../get-started/readme.md

does not follow this principle even in English

I believe that omitting your own deficiencies is easier.
I also understand that not having a software life cycle is easier 
https://github.com/stellar/stellar-core/milestones
https://github.com/stellar/docs/milestones

or even as I commented above  Common Vulnerabilities and Exposures  ( CVE ). 
( that google and Fb products have. This part you know right? ) 

so the problem is not you do not, just.
but be picky about things that are not important.
and neglect those that are. such as understanding basic concepts natively and Cyber Security.
