### ISSUE TITLE
Federation query parameters are wrong

### ISSUE THREAD

**Issue by johansten** [stellar/docs#35]
The docs says to use "destination", but "destination" gives an error, whereas "user" gets the correct answer.

**Comment by johansten** [comment]
... or api.stellar.org just does the wrong thing in the federation end point.

**Comment by bartekn** [comment]
It works me: https://api.stellar.org/federation?destination=bartekn&domain=stellar.org
Can you point to the exact sentence in our docs which might be misleading?

**Comment by johansten** [comment]
It's working for me too now, but when I tried it two days ago I got error messages if I used destination instead of user. Old servers hanging around? user/destination both seem to be working now.
