### ISSUE TITLE
Include Scala SDK on https://www.stellar.org/developers/

### ISSUE THREAD

**Issue by Synesso** [stellar/docs#356]
Can we please include a link to [Scala](https://github.com/Synesso/scala-stellar-sdk) under **Reference & SDKs** on https://www.stellar.org/developers/ ?

**Comment by Synesso** [comment]
I wanted to, but I can't find the source for the landing page in this repo. I can see everything else, but not https://www.stellar.org/developers/

**Comment by Synesso** [comment]
I didn't trust github search, so I cloned this repo and searched for the landing page. It's not here. Is it in a different repo, or private?

**Comment by bartekn** [comment]
It here: https://github.com/stellar/developers/blob/master/src/index.handlebars#L52
