### ISSUE TITLE
How Best to Pull Request Translations

### ISSUE THREAD

**Issue by pedropran** [stellar/docs#388]
Hello,

I finished translating the whole docs/guides section into Brazilian Portuguese (pt-BR). ([Take a look here.](https://github.com/swipetech/docs/tree/pt-BR)) 

Since this pull request should not go directly into the master branch, I would like to propose a new parallel branch.

I understand there haven't been any cases like this before. What would be the best way to submit this pull request?

Thanks.

**Comment by bartekn** [comment]
Thanks for this work. I think you can simply create a PR to the main repo and we will create a new branch with your translation. We won't be able to support translations (like displaying them at www.stellar.org/developers) because of the reasons I described here: #329.

**Comment by pedropran** [comment]
Great! 

I hope this can help Portuguese-speaking developers test out Stellar, and also inspire other translations.

@EvertonMelo, you can check out our translation [here](https://github.com/swipetech/docs/tree/pt-BR).

**Comment by theaeolianmachine** [comment]
Hey @bartekn - I was just looking at this - would you rather this be in a separate directory or a separate branch? I think a directory seems more reasonable (easier to find, even if it's not on the main site).

**Comment by bartekn** [comment]
Yeah, I agree that a separate directory would be more accessible. We should probably do something like:
```
├── ...
├── translations (new directory)
│   ├── pt-BR (each language has a directory)
│   └── readme.md (explaining that it's community maintained, can be out of date, etc.)
└── ...
```

**Comment by theaeolianmachine** [comment]
@pedropran would you be willing to modify #390 to put it in a separate directory, along with a README like in @bartekn's example?

**Comment by pedropran** [comment]
@theaeolianmachine I just updated it with these changes.
