### ISSUE TITLE
document when testnet is "reset"

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/docs#398]
How often?
How can I as a developer know that testnet is going to be reset?

**Comment by bartekn** [comment]
Fixed in https://github.com/stellar/docs/pull/397 ?

**Comment by zachalam** [comment]
Thanks for taking the task @theaeolianmachine, are there any updates at this time?

**Comment by theaeolianmachine** [comment]
See https://github.com/stellar/docs/pull/411 for further updates, but the gist is that we'll be resetting it once a quarter starting in 2019.

**Comment by zachalam** [comment]
Thanks @theaeolianmachine - I'll be looking out for the finalized schedule. Thanks for the update.

**Comment by theaeolianmachine** [comment]
Closing this out, as this was completed in #411 and other commits ([see here](https://www.stellar.org/developers/guides/concepts/test-net.html#periodic-reset-of-testnet-data))
