### ISSUE TITLE
Editing diagrams, tools & sources

### ISSUE THREAD

**Issue by lazaridiscom** [stellar/docs#400]
Which tools must one use to edit the diagrams within:

https://github.com/stellar/docs/tree/master/guides/anchor/assets

and where are the sources?

**Comment by theaeolianmachine** [comment]
There aren't any source files for these diagrams present - do you have any intent to update these, and if so, what are you looking to do?

**Comment by lazaridiscom** [comment]
I don't even remember what I wanted to do, but most possibly it was an curiosity/general-nature inquiry:

* The diagramms look nice, so, curious, what too you use.
* And then: open sources, the diagramms are an integral part of the sources (docs) and should be editable (just in case someone wants to work on them).

In any way: at least you have(!) diagramms (many other projects don't).

**Comment by theaeolianmachine** [comment]
Yeah, if I had to guess it was done in Adobe Suite (Photoshop, Illustrator, etc.) but honestly might have been done even with software like Keynote (and if anything, there are other good options out there like Affinity Designer).

We definitely welcome any new sources that you think would be valuable though, and when we look into various parts of the website we're overhauling this quarter I'll mention the idea of posting image sources under Creative Commons and see where we go from there.

Thanks!
