### ISSUE TITLE
There are 3 ways to issue accounts for customers, not 2 ways

### ISSUE THREAD

**Issue by skirsch** [stellar/docs#401]
https://www.stellar.org/developers/guides/anchor/ was VERY confusing to a newbie. It said that there are only two ways to handle your customers if you are an anchor. 

But most anchors don't do it either of those ways... they use the user's existing account and optionally set auth required and revocable.

Why not talk about the most common case here? As an anchor, I went right to this part of the doc and was super confused since everyone was else wasn't doing it in the way described.

**Comment by theaeolianmachine** [comment]
Merging this into #413, as we'll be rewriting the entire guide in a few months.
