### ISSUE TITLE
need a bit more info on address and phone number format in TOML file

### ISSUE THREAD

**Issue by skirsch** [stellar/docs#404]
Does it matter?
https://www.stellar.org/developers/guides/walkthroughs/how-to-complete-stellar-toml.html

should the state have a comma after it? or can i write San Jose, CA 94567?

for the phone number, that seems like a weird format. Can I do +1-213-555-5555?

**Comment by theaeolianmachine** [comment]
I don't believe there's anything that actually matters for parsing here, but agree that we should document that. Thanks for sending over!

**Comment by theaeolianmachine** [comment]
Closing this out in favor of https://github.com/stellar/stellar-protocol/pull/301 and #325.
