### ISSUE TITLE
Broken links to docs on stellar.org

### ISSUE THREAD

**Issue by kennygrant** [stellar/docs#41]
Your website https://launch.stellar.org links in several prominent places to docs on github which don't exist anymore or have been renamed. I followed these two links trying to find out about gateways. 

https://launch.stellar.org/#/dashboard ->
https://github.com/stellar/docs/blob/master/docs/Adding-Multiple-Currencies.md

https://www.stellar.org/developers/ -> 
https://github.com/stellar/docs/blob/master/docs/gateway-introduction.md

**Comment by bekkibolthouse** [comment]
Thank you @kennygrant we'll get these updated.

**Comment by irisli** [comment]
These have been resolved
