### ISSUE TITLE
Revamp Asset Issuance Guide

### ISSUE THREAD

**Issue by theaeolianmachine** [stellar/docs#413]
There are currently several docs that cover asset issuance in Stellar:

https://www.stellar.org/developers/guides/issuing-assets.html
https://www.stellar.org/developers/guides/walkthroughs/custom-assets.html
https://www.stellar.org/developers/guides/concepts/assets.html#anchors-issuing-assets

Along with an internal guide at SDF. We should refactor these into a single comprehensive guide on our public docs.

We also need to merge parts of the anchor guide in there, and refactor this out:
https://www.stellar.org/developers/guides/anchor/

**Comment by theaeolianmachine** [comment]
Additional feedback can be found in #401.

**Comment by rice2000** [comment]
Closing this issue since it's covered in the inventory of new docs to write.
