### ISSUE TITLE
Delete offer needs documenting

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/docs#445]
To delete an offer, https://www.stellar.org/developers/guides/concepts/list-of-operations.html#manage-offer implies that you need to provide all manage offer parameters correctly, and then set the `amount` to 0. This is not true.

The reality (confirmed by experiment) is
1. Stellar core doesn't care about what's in any of these fields except the amount.
2. Horizon will reject Manage Offer if it is missing any fields.
3. Horizon will also reject Manage Offer if Buying == Selling.

So that means that the only piece of information a user *actually* needs to delete an offer is the offer ID. *However*, in order to pass validation, said user must provide dummy values for the other fields. An SDK can hide this silliness behind a helper function.

This is more than just an intellectual curiosity, because an SDK with a signature like this:

`func DeleteOffer(offerID uint64) ManageOffer`

is much cleaner for a user than a signature like this:

`func DeleteOffer(selling, buying *Asset, amount, price string, offerID uint64) ManageOffer`

The doc should be updated to indicate that the values of the other args don't matter in the delete case, so that SDK writers can code accordingly.

For completeness, I'll note that `update offer` does not have this benefit. `update offer` will not succeed with untrusted assets. It *may* succeed with the wrong assets (I didn't test this), as long as they are trusted. But that doesn't help anyone at all, so doesn't seem necessary to document.

**Comment by rice2000** [comment]
Looks like this issue was resolved a while ago (when sell offers were introduced), and that the current docs reflect that change.  So I think we're good here.
