### ISSUE TITLE
Best Practice: Use friendbot to fund "Account Creation Account" on Testnet

### ISSUE THREAD

**Issue by MikeFair** [stellar/docs#446]
[Posting this from a conversation on the dev_discussion Keybase channel.]

Currently the Create Account examples oftentimes show the code for using friendbot to Create Accounts.  Unfortunately this technique is oftentimes used as the only way their app/code creates accounts which obviously becomes an issue when they move to mainnet.

This issue suggests adopting/recommending the following as a best practice:  
All devs should maintain an "Account Creator Account" of their own/for each app. Provide example code for a function which takes (key, amount) as parameters that will create an account given a public key, a private key, or generate a random key if the key parameter is blank/null, and uses some default amount (say 10 XLM?) if the amount parameter is not provided (developers can adjust this default amount as they see fit).

Use friendbot to fund this "Account Creator Account", then whenever this Account gets low on XLM, have the function use friendbot to create/fund a random account and execute a merge operation of that account into the "Account Creator Account" to refill it.

This reinforces that you will need an "Account Creator Account" of your own for your app, and introduces the idea of having to manage a secret key for this account.  One concern is it likely encourages people to put the secret key directly into their checked in development code.  It'd be good if this code also gave ideas for how to avoid doing that, but obviously isn't required.

**Comment by rice2000** [comment]
Filed as an issue in the new docs:
https://github.com/stellar/new-docs/issues/282
