### ISSUE TITLE
Document ALLOW_TRUST_SELF_NOT_ALLOWED

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/docs#448]
In [List of Operations](https://github.com/stellar/docs/blob/master/guides/concepts/list-of-operations.md), `change trust` is missing documentation for the error code [ALLOW_TRUST_SELF_NOT_ALLOWED](https://github.com/stellar/stellar-core/blob/4531e9af7136bb3f80400093542f6589512043b6/src/xdr/Stellar-transaction.x#L620).

**Comment by theaeolianmachine** [comment]
:) I ran into this the other day while updating the examples, so I agree we should mention it (as well as the fact that you need two accounts to create an asset — you can't just make an asset for yourself).
