### ISSUE TITLE
Add documentation on destroying assets (getting liquidity)

### ISSUE THREAD

**Issue by theaeolianmachine** [stellar/docs#449]
From Tom Q.

I was just chatting with Patrick @ Keybase, he suggested we should add docs on how to destroy issued assets to this page: https://www.stellar.org/developers/guides/walkthroughs/custom-assets.html

Namely the way to do this is to send the payment to the issuer, and then they give you liquidity. When a payment is sent to the issuer, those tokens are removed the circulation pool.

**Comment by tomquisel** [comment]
@theaeolianmachine can you prioritize this? We had a question about it yesterday.
