### ISSUE TITLE
Clean up Contribution Guide

### ISSUE THREAD

**Issue by theaeolianmachine** [stellar/docs#479]
This should just mirror what's in Github otherwise: https://www.stellar.org/developers/guides/contributing.html

**Comment by ire-and-curses** [comment]
I think it's actually this doc: https://github.com/stellar/docs/blob/master/CONTRIBUTING.md

Which I totally agree should be simplified and updated!

**Comment by theaeolianmachine** [comment]
Closing this out to clean up my created issues across Github open source repos that are no longer relevant to me. If this is still an issue, please make a new issue to represent it.
