### ISSUE TITLE
Validators Guide - Running Stellar Core

### ISSUE THREAD

**Issue by theaeolianmachine** [stellar/docs#481]
Create a comprehensive guide that focuses on running and maintaining a Stellar Core instance at a base level for validators. It should reference the admin guide, but should ideally be more high-level and focus on making it dead simple to run a node.

It should also include information on automatic quorum generation once it's been released in v11.2.0.

**Comment by rice2000** [comment]
Closing this issue since it's covered in the inventory of new docs to write.
