### ISSUE TITLE
Define testnet best practice of merging XLM back to Friendbot's account

### ISSUE THREAD

**Issue by tomquisel** [stellar/docs#490]
We have a problem right now where friendbot's XLM account is drained quickly. Ideally devs on testnet would merge their accounts back into friendbot when they're done with automated tests, refilling its XLM reserve. We should recommend that devs do this [here](https://www.stellar.org/developers/guides/concepts/test-net.html#best-practices-for-using-testnet) and give instructions on how to do it.

Here's a [Gist](https://github.com/stellar/go/blob/cae2d21e69a81eb7b29b837b4d7a28de4753d7af/txnbuild/cmd/demo/operations/demo.go#L80) from @ire-and-curses demonstrating how to clean up and merge accounts in Go.

**Comment by rice2000** [comment]
Refiled in new docs: https://github.com/stellar/new-docs/issues/283
