### ISSUE TITLE
A lot of dead links on the developer guide

### ISSUE THREAD

**Issue by ykcai** [stellar/docs#493]
https://www.stellar.org/developers/horizon/reference/
https://www.stellar.org/developers/stellar-core/software/admin.html
https://www.stellar.org/developers/guides/concepts/scp.html
https://www.stellar.org/developers/guides/concepts/test-net.html
https://www.stellar.org/developers/guides/get-started/create-account.html

Not sure if this is expected but I will add onto this if I see anymore...

**Comment by rice2000** [comment]
Interesting.  The first link is giving me a 503 error.  The rest of them work fine for me, though.

**Comment by bartekn** [comment]
This is now fixed.
