### ISSUE TITLE
Anchor guide page is out of date

### ISSUE THREAD

**Issue by vitchor** [stellar/docs#511]
It seems like there's an out-of-date anchor guide page here: https://www.stellar.org/developers/guides/anchor/. 

This page is accessible from the very bottom part of the “Custom Assets” walkthrough section.

@rice2000, @tomquisel suggests it:
a) shouldn't be linked to;
b) should be updated soon.

Does this make sense? Thanks and kind regards!

**Comment by rice2000** [comment]
Good catch!  I'll take out the link pending the update.

**Comment by rice2000** [comment]
Made the update.  Thanks for the keen eye!
