### ISSUE TITLE
Add more recommended hosting providers with good prices

### ISSUE THREAD

**Issue by dilawfird** [stellar/docs#518]
Here https://www.stellar.org/developers/guides/hardware.html
the recommended server cost $0.34/hr on aws and every one can't put that much on a server, it costs around 244 dollars a month, can we change the doc  and recommend servers that cost around 50-80 dollars but I'm just starting using stella core and horizon so I don't know a lot I need some time to test different servers.

So if any one that knows well stellar core and horizon please feel free to share with us your recommended hosting provider with good prices.

**Comment by tomquisel** [comment]
@rice2000 In fact, this doc is pretty out of date. I don't think we should mention bridge or compliance server. Also, that federation server seems way over-specced. Also, [blockdaemon](https://blockdaemon.com/stellar-protocol-details/) should be a bigger part of the conversation given it's so inexpensive and easier.

**Comment by dilawfird** [comment]
@tomquisel Thanks for your answer.
