### ISSUE TITLE
Add PathPaymentStrictSend to list of operations

### ISSUE THREAD

**Issue by bartekn** [stellar/docs#520]
[CAP-24](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0024.md) introduces a new `PathPaymentStrictSend` operation. We should add it here: https://www.stellar.org/developers/guides/concepts/list-of-operations.html

CC: @rice2000

**Comment by rice2000** [comment]
Solved by https://github.com/stellar/docs/pull/528
