### ISSUE TITLE
Update Go example code in Getting Started guide 

### ISSUE THREAD

**Issue by jstemmer** [stellar/docs#525]
The Go code examples in the Getting Started guide use the deprecated [clients/horizon](https://godoc.org/github.com/stellar/go/clients/horizon) and [build](https://godoc.org/github.com/stellar/go/build) packages. Since this is likely to be used by people new to the project, let's update them to use the new [clients/horizonclient](https://godoc.org/github.com/stellar/go/clients/horizonclient) and [txnbuild](https://godoc.org/github.com/stellar/go/txnbuild) packages.

See here:
https://www.stellar.org/developers/guides/get-started/create-account.html
https://www.stellar.org/developers/guides/get-started/transactions.html

**Comment by ire-and-curses** [comment]
Related: https://github.com/stellar/go/issues/1222

**Comment by jstemmer** [comment]
Also: https://www.stellar.org/developers/guides/issuing-assets.html

**Comment by rice2000** [comment]
These were updated in the new docs.
