### ISSUE TITLE
Incorrect command for generating keys in example config

### ISSUE THREAD

**Issue by usa51008** [stellar/docs#539]
### What version are you using?

12.2.0

### What did you do?

I tried to generate a public/secret key pair. Using line 5 in https://github.com/stellar/docs/blob/master/other/stellar-core-validator-example.cfg

### What did you expect to see?

> run `stellar-core gen-seed` to generate a public key and secret seed.

### What did you see instead?

>  run `stellar-core --genseed` to generate a public key and secret seed.

**Comment by usa51008** [comment]
Sorry, first-time contributor via Github, missed the guide to contributing.  Will follow the procedure for documentation issues.  Looking forward to contributing.

Lou

**Comment by vcarl** [comment]
Thanks for bringing this to our attention! Very helpful.
