### ISSUE TITLE
core example file is outdated

### ISSUE THREAD

**Issue by MonsieurNicolas** [stellar/docs#541]
As we're simplifying the documentation, we should remove `docs/other/stellar-core-validator-example.cfg` and instead ask people a few questions to help them get started to fill the key configuration elements from the core config.

Right now instead of teaching people how to pick their quorum set "the right way", it provides a configuration that has several issues:
* this configuration is an arbitrary configuration that will always end up being out of sync with the [real stellar-core reference](https://github.com/stellar/stellar-core/blob/master/docs/stellar-core_example.cfg)
* this configuration points to arbitrary validators (instead of tier-1)
* this configuration uses old-style quorum configuration that is error prone
* this configuration points to arbitrary peers

**Comment by rice2000** [comment]
Fixed in new docs.
