### ISSUE TITLE
[Crowdfunding example] Is it possible to presign a manage buy offer without a concrete amount?

### ISSUE THREAD

**Issue by d0x** [stellar/docs#547]
The example doesn't make clear how it's possible to create a valid `Manage Buy Offer` in Transaction 5 of the [crowdfunding example](https://www.stellar.org/developers/guides/walkthroughs/stellar-smart-contracts.html#transaction-5-crowdfunding-fails) from the stellar smart contracts reference.

The reference quotes:

> Manage Buy Offer: Holding account buys participation tokens at a rate of X per token.

But at the time of presigning I don't know how many participation tokens were sold. So which amount should I put into the buy offer?

With the full amount of participation tokens we get `op_underfunded` and without an amount I get `op_malformed`.
https://www.stellar.org/developers/guides/walkthroughs/stellar-smart-contracts.html#transaction-5-crowdfunding-fails

**Comment by rice2000** [comment]
Filed related issue in the new docs: https://github.com/stellar/new-docs/issues/284
