### ISSUE TITLE
Stellar-core docs provide example of quorum which does not pass isQuorumSetSane() check

### ISSUE THREAD

**Issue by AndrejMitrovic** [stellar/docs#553]
https://docs.stellarcn.org/stellar-core/software/admin.html#picking-thresholds

The docs show one possible quorum example:

```
[ 67%, A, B, C, [50%, D, E]] # D or E only required if one of A,B,C doesn’t agree 
(the [D,E] group acts as a tie breaker)
```

This is essentially a quorum config with (pseudocode):

```
SCPQuorum {
    threshold : 3
    validators : {A, B, C}
    SCPQuorum { threshold : 1, validators : D, E }
}
```

However when calling `isQuorumSetSane()` with such a quorum and with `extraChecks` enabled, the function returns `false`.

----

Is the documented example wrong? Or is it just expected to be unsafe and we have to use `false` for the `extraChecks` parameter in this case?

CC @MonsieurNicolas

**Comment by rice2000** [comment]
The link you shared is from stellarcn.org, which appears to be an out-of-date translation of the docs.   Even though it links to this github repo, the section you're pointing out isn't here anymore.  
 It's been replaced by this section explaining how Stellar-core automatically generates quorum sets:
https://github.com/stellar/stellar-core/blob/master/docs/software/admin.md#choosing-your-quorum-set

FYI: the docs portal that's maintained, and that draws from this repo is at:
https://www.stellar.org/developers/ 

The current Stellar-core admin guide is here:
https://www.stellar.org/developers/stellar-core/software/admin

**Comment by rice2000** [comment]
I went ahead and closed this issue since it's not something we can fix on our end, though I will try reaching out to the people listed in the stellarcn repo.   

Question for you, @AndrejMitrovic: do you know how you ended up on that page instead of the stellar.org docs?  I'd like to try to ensure that developers discover and consult the version that we keep up to date, and I'm trying to figure out what that would entail.

**Comment by AndrejMitrovic** [comment]
It was through a google search. I haven't even realized I was not on the official stellar website. Thanks for noticing that! So closing it was right.

Thank you.
