### ISSUE TITLE
Add information about cache HTTP headers required for history archives

### ISSUE THREAD

**Issue by bartekn** [stellar/docs#557]
`.well-known/stellar-history.json` responses should have cache headers (`Cache-Control: no-cache` and possibly `Expires` for old proxies) because it changes every ~5 minutes and it's possible that a browser or a proxy will cache this file and make the content stale. I was thinking about adding this to https://github.com/stellar/stellar-core/blob/master/docs/history.md but it doesn't really explain admin part of history archive. Maybe we should add this to "Admin guide"?

See: https://github.com/stellar/go/issues/2350#issuecomment-595362057

**Comment by brahman81** [comment]
we document the process of publishing a history archive, including cache headers in the packages docs. Would be good to unify docs.

https://github.com/stellar/packages/blob/master/docs/publishing-a-history-archive.md#caching-and-history-archives

**Comment by MonsieurNicolas** [comment]
I think @rice2000 is working on a new admin guide? I agree this would have to be in the "full validator" guide

**Comment by rice2000** [comment]
The new docs include this info in the `Run a Core Node` section.
