### ISSUE TITLE
Add “Moving into production” guide; Add passphrase doc

### ISSUE THREAD

**Issue by nullstyle** [stellar/docs#69]
The “network passphrase” concept is important and not really covered in our documentation anywhere.

We should add a guide that introduces the changes necessary to an integration to ensure it works on the public network.

**Comment by irisli** [comment]
It would also be important to explain this information in the docs about transactions.

**Comment by bartekn** [comment]
I noticed that some of devs on slack are also creating their private networks. So we should add "Networks" article to concepts explaining where passpharases are used and how to use our SDK to make it work with other networks.
