### ISSUE TITLE
"Amounts" article

### ISSUE THREAD

**Issue by bartekn** [stellar/docs#76]
To explain the format of amounts in operations.

**Comment by bartekn** [comment]
Should probably also contain information about Price.

**Comment by jedmccaleb** [comment]
This should probably just be expanded: https://www.stellar.org/developers/learn/concepts/assets.html

**Comment by bartekn** [comment]
Oh, haven't seen this. But we should probably add information about stroops and that other assets amounts need to be multiplied by 10^7.

**Comment by irisli** [comment]
I just came here because I was looking for this article. We should probably have a section about precision and recommending people to use integer or BigNum libraries and not floats.

**Comment by irisli** [comment]
I've written documentation about amounts. I will open a new issue for Price.
